name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.5.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: react-responsive-modal

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: yarn install --immutable
        if: ${{ steps.release.outputs.release_created }}

      - name: Build
        run: yarn build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish npm package
        run: yarn npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
